### ISSUE TITLE
Required headers for /user lookup

### ISSUE THREAD

**Issue by ZachWhitford** [Alkaar/resy-booking-bot#12]
Which headers did you find were required for the /user endpoint lookup? Getting a 419 back from the endpoint while it seems I'm using all the same ones as you. Any pointers?

**Comment by ZachWhitford** [comment]
Just to clarify as well, the exact same request works on non /user endpoints so there must have been a backend change but would love your opinion

**Comment by Alkaar** [comment]
Sorry for not keeping up to date on these issues as I've not used nor maintained the bot due to the pandemic. As of now, it seems that Resy updated the API endpoint so the contract is completely different. I have tried to go through the bot to fix things but I haven't gotten around to fixing it completely. Just wanted to make you all aware.

**Comment by ZachWhitford** [comment]
I have figured out a bypass and the new endpoint.

**Comment by Alkaar** [comment]
Glad you figured it out. FYI I updated the bot to work with the new Resy API along with a few minor fixes. LMK your thoughts on it.

Regarding the endpoints, the `/user` endpoint is not used in the code. I left it in there anyway because I originally was using it to write the bot and then realized later on I didn't need it. Felt it didn't hurt to leave it there as a reference.

**Comment by Alkaar** [comment]
Just to update this thread, I decided to remove the `/user` endpoint completely to avoid confusion. If there's a use case for it, I can always bring it back.
