### ISSUE TITLE
I'm getting an error downloading com.typesafe.play:play-ahc-ws_2.13:2.6.11

### ISSUE THREAD

**Issue by OilerWass** [Alkaar/resy-booking-bot#14]
It appears this URL is no longer working:
https://repo1.maven.org/maven2/com/typesafe/play/play-ahc-ws_2.13/2.6.11/play-ahc-ws_2.13-2.6.11.pom

**Comment by michaelcgold** [comment]
this is easy to fix

**Comment by Alkaar** [comment]
Sorry for not keeping up to date on these issues as I've not used nor maintained the bot due to the pandemic. As of now, it seems that Resy updated the API endpoint so the contract is completely different. I have tried to go through the bot to fix things but I haven't gotten around to fixing it completely. Just wanted to make you all aware.

**Comment by freeeking** [comment]
> Sorry for not keeping up to date on these issues as I've not used nor maintained the bot due to the pandemic. As of now, it seems that Resy updated the API endpoint so the contract is completely different. I have tried to go through the bot to fix things but I haven't gotten around to fixing it completely. Just wanted to make you all aware.

Does it work though?

**Comment by danielweisman** [comment]
Hey Alkaar - any updates here?  Have you fixed the bot to work with the new API?

**Comment by Alkaar** [comment]
Hey, took a little longer to come back to this but I did fix the bot to work with the new Resy API along with a few other changes on top of updating some of the dependencies. Give it a shot and LMK how it goes.
