### ISSUE TITLE
Getting some errors when running the build

### ISSUE THREAD

**Issue by EddiOS42** [Alkaar/resy-booking-bot#27]
I've added all the values in but when I type "sbt run" and enter, it shows these errors.

![Screen Shot 2022-08-14 at 4 26 00 PM](https://user-images.githubusercontent.com/90667316/184558793-a52ee4d4-8ec6-4b10-9121-2485dcc39822.jpg)

**Comment by Alkaar** [comment]
It looks like it failed on compile. My guess is while you were adding the values in, you must have missed a brace or something which is why it's complaining.

**Comment by EddiOS42** [comment]
Thanks, II figured it was some syntax issues. The last error its's throwing me is for the resTimeTypes. I'm not quite sure what's the correct format for the sequence.
![Screen Shot 2022-08-14 at 8 59 48 PM](https://user-images.githubusercontent.com/90667316/184574983-2622b7af-ed8c-4cb6-af2f-7d9231ecbb07.jpg)

**Comment by Alkaar** [comment]
The implementation of the case class can be found in `ResyBookingBot.scala` at the bottom which will give you some hint.

```scala
final case class ReservationDetails(
  date: String,
  partySize: Int,
  venueId: Int,
  resTimeTypes: Seq[ReservationTimeType]
)

final case class ReservationTimeType(reservationTime: String, tableType: Option[String] = None)
```

As you can see, it's a `Seq` of `ReservationTimeType` which takes two parameters, a String and an Option of String. So you would have to pass something like the following...

```scala
Seq(ReservationTimeType("18:00:00", Some("Patio")))
```

One other tiny tip though. I made a convenience function (see below) so that you don't have to pass a `Some` or `None` for the tableType.

```scala
object ReservationTimeType {

  def apply(reservationTime: String, tableType: String): ReservationTimeType = {
    ReservationTimeType(reservationTime, Some(tableType))
  }
}
```

So with the above convience function, you can just do...

```scala
Seq(ReservationTimeType("18:00:00", "Patio"))
```

**Comment by EddiOS42** [comment]
Thank you for explaining it in detail!

**Comment by Alkaar** [comment]
FYI since a lot of people had some confusion around how to set the reservation time and table type, I made a change to hopefully make this a little bit more clear 👉 https://github.com/Alkaar/resy-booking-bot/pull/54
