### ISSUE TITLE
Thanks for creating this! Set-up question

### ISSUE THREAD

**Issue by J-clouds** [Alkaar/resy-booking-bot#53]
Thanks so much for creating this! I've struggled with getting resy's at so many NYC restaurants so I really appreciate you creating this. That said, I'm pretty new to coding so I have a few basic questions if that's alright. To run this code, do I just download IntelliJ [here](https://www.jetbrains.com/idea/download/#section=windows)? (I downloaded the EDU version because it's free & I'm just learning tbh.)

After I download it and the file you provided, I tried to run it but got an error: Cannot determine Java VM executable in selected JDK

I tried to find the com.resy.ResyBookingBot file to configure the main class, but couldn't find it - where exactly should I be looking? Here's the screenshot of the issue:
![image](https://user-images.githubusercontent.com/81653086/194799173-419109c7-44ec-4c71-83c8-43f511583f5f.png)

Your help is much appreciated!

**Comment by Alkaar** [comment]
The version of IntelliJ you have is fine.

Properly opening this repo inside IntelliJ is less about this project and more about just using IntelliJ and coding in general. I think you're going to have to do a bit of learning and digging yourself since it would be a bit much to explain it all here. From what you shared, it doesn't look like you opened the project correctly because the left side should list all the files which it doesn't. Also, it doesn't seem to be able to find the right Java/JDK version so maybe you have to set it somewhere in IntelliJ. After fixing those two, you may run into other issues but again, these are more general coding/IntelliJ questions for which there should be a wealth of material about this on the internet with a quick google.

Hope this gives you a bit of guidance on what to do next.

**Comment by J-clouds** [comment]
I see - I give this a harder try. Thanks for your response.
