### ISSUE TITLE
Error: Could not find or load main class ResyBookingBot - How do I Configure to Look under com.resy.ResyBookBot?

### ISSUE THREAD

**Issue by lorenzocarlo1** [Alkaar/resy-booking-bot#63]
What are the steps to configuring it to look under com.resy.ResyBookingBot?

I have barely any coding experience but have been able to execute every step until I hit run and get the error message Error: Could not find or load main class ResyBookingBot and I'm not sure what I'm supposed to do to have it find the main class.

Thank you so much

**Comment by Alkaar** [comment]
A lot of people have used my bot without a programming background and that's ok! But that also means a lot of questions are generic ones that can be found on googling and not specific to this repo. Your question is no different and It's hard to give direct instructions so I would also suggest you google it.

Also, I would also suggest looking at the closed issues since a lot of these questions have been asked so you may find your answer there as well 👉 https://github.com/Alkaar/resy-booking-bot/issues/11

**Comment by Alkaar** [comment]
Please LMK if this addresses your issue or not. Otherwise, I will close this issue out.

**Comment by Alkaar** [comment]
Didn't hear back so closing this issue out.
