### ISSUE TITLE
Random Times

### ISSUE THREAD

**Issue by dukepolarbear** [Alkaar/resy-booking-bot#67]
Hey Alkaar, thanks for making this! Got it setup about a month ago, a problem I'm having is not relying on a single reservation time slot. I tried to tweak the code to support a random time in a ton of different ways to no avail, my java is a bit rusty. How would I be able to set it to randomly select a time slot based on the obvious factors, specific restaurant id, party size, etc. 

Thanks again!

**Comment by Alkaar** [comment]
Curious why you want to support a "random time" or perhaps you mean support looking at more times? It already supports a priority list of times which is mentioned in the documentation. Would that fit your use case?

**Comment by dukepolarbear** [comment]
Yeah, sorry, meant looking at more times, so I wouldn't have to guess which time was available. Was on a much later version so I didn't notice. Thanks so much, Have you ever tried the bot on Carbone? Or is that too popular that I wouldn't have a chance? Thanks again, going to send you something on the buy me a coffee link you posted because the bot is great!

**Comment by Alkaar** [comment]
So I made some tweaks later on to make major updates and releases more visible. Going forward, all future changes are tagged and released with clearer release notes. Hopefully, this should help with the visibility.

Only tried Carbone once or twice and got nothing. Need to mess with it some more but haven't had the time.

Appreciate the ❤️, monetary or not! I have some stuff I'd like to do but just haven't had the time since I do this purely for fun. If life and work frees up then maybe I can get back into it but I at least try to respond to comments I get.

**Comment by Alkaar** [comment]
I'm assuming this is resolved so closing this out
