### ISSUE TITLE
Adjust the start date and time?

### ISSUE THREAD

**Issue by jschaeuf01** [Alkaar/resy-booking-bot#7]
Is there a way to adjust the code to start trying to get a reservation a different number of days in advance, other than 30? Same question about it starting at midnight. Could the code be adjusted to start trying to get a reservation at say 3am?

**Comment by derfong** [comment]
Certainly, the code could be configured to make this easier.  I've been wanting to revisit this code again and clean it up a bit since I've improved a bit more in my Scala over the past two years.

Regarding changing the day you want to get a reservation, that's already configurable.  Just change the date you want to grab here:
https://github.com/Alkaar/resy-booking-bot/blob/master/src/main/scala/com/resy/BookingDetails.scala#L11

Regarding changing the time you want the bot to fire, you can change this part of the code to wait for whatever length of time you need.  You'll have to add to that variable 3 hours in milliseconds to make it fire at 3 AM. It's not easily configurable right but that is a simple change that can be done.
https://github.com/Alkaar/resy-booking-bot/blob/master/src/main/scala/com/resy/ResyBookingBot.scala#L18

**Comment by Alkaar** [comment]
Just to update this closed issue, I've made the start date and time more configurable and easier to use. Since most reservations become available daily, you can now specify what time you want the bot to fire and it will automatically calculate the next snipe time for you!

**Comment by FracturedWinter** [comment]
Have this running successfully (successfully booked reservations), but the bot doesn't "wake" from sleep when a reservation window opens the following day. Any troubleshooting ideas?

**Comment by Alkaar** [comment]
You can comment out the `system.scheduler.scheduleOnce(millisUntilTomorrow millis)` part which is what causes the bot ot wait. Alternatively, you can set the bot to run within the next minute.

Out of curiosity, how are you running it?

**Comment by FracturedWinter** [comment]
Thanks - will try that today.  

Running from the IntelliJ sbt shell on Mac (Intel).

To troubleshoot for easy reservations, had just changed the else statement to 0 from 1.

    val nextSnipeTime =
      if (todaysSnipeTime.getMillis > dateTimeNow.getMillis) todaysSnipeTime
      else todaysSnipeTime.plusDays(0)

**Comment by Alkaar** [comment]
Ah I slightly misread your first comment @FracturedWinter. I thought it wasn't sniping at all and missed that it's not working for you when you snipe reservations for tomorrow.

Are you sure the bot is still running when it's time for the bot to wake up? I'd be curious if you have a concrete example or more details on a specific use case to help me reproduce your issue. I've tested this the day of a reservation and the night before and have not run into any issues. I've done this with both running it in IntelliJ and on CLI via sbt. I've not tried running it from CLI  via sbt from _within_ IntelliJ.

That piece of code you highlighted calculates the next snipe time based off of the snipe time you entered in `snipeTime`. If the `snipeTime` is after the current time, it will try to snipe today. If the `snipeTime` is before the current time, it will try to snipe tomorrow. The `plusDays(1)` is necessary if today's `snipeTime` has already passed and it needs to snipe tomorrow.

**Comment by FracturedWinter** [comment]
Overnight behavior resolved itself, didn't find a specific cause.

One discovery not mentioned in the readme is an incorrectly specified table type (vs. None) will result in no reservation i.e. "Dining Room" if venue uses "Indoor."  Not sure it warrants an issue. 

Thanks again for building the bot.

**Comment by Alkaar** [comment]
> Overnight behavior resolved itself, didn't find a specific cause.

LMK if it comes up again

> One discovery not mentioned in the readme is an incorrectly specified table type (vs. None) will result in no reservation i.e. "Dining Room" if venue uses "Indoor." Not sure it warrants an issue.

This I know but I figured it can be somewhat inferred. It would be the same as specifying a reservation time that doesn't exist. There's no easy way to fuzzy match on table type since it varies so much from restaurant to restaurant. I tried to make this better by allowing to either not specify table type and to allow for a case insensitive matching on table type.

I can keep this in mind though if others raise this as a concern or if someone has a better idea.

> Thanks again for building the bot.

Glad you're enjoying it! 🚀

**Comment by abaileyb** [comment]
@Alkaar, how would you recommend finding the correct labeling of table type for restaurants where there is almost never availability (ie somewhere like Carbone)?

**Comment by Alkaar** [comment]
There are two ways to do this though require a tiny bit of technical know-how:
- Change the logging level to debug so you will see all the logging. When you snipe, you will be able to see the table types that are available and you can choose from there.
- When visiting the resy page for a specific restaurant, there is a part of the JSON response that actually returns what table types are available to select from.

FYI the table type is a case-insensitive search so that helps in the case of minor typos.
