### ISSUE TITLE
Payment method struggles

### ISSUE THREAD

**Issue by btbeal** [Alkaar/resy-booking-bot#73]
Hey - really impressed by all the awesome work here!! I'm working on something similar in my spare time but can't request for restaurants where payment methods are required. I can access my preferred payment id via the API... just can't seem to use it. Because I know ~0 scala, I'm trying to understand **what the booking POST looks like with payment methods**?

From your code, I was assuming the body of the post would be something like this:

```
 {"book_token":["my_token"],"struct_payment_method":{"id":[1234]}} 
```

But this doesn't seem to work. 

I would love some info on (1) the format [this](https://github.com/Alkaar/resy-booking-bot/blob/b6ba39813c5a033e0aed973fa0ccf204cdf79559/src/main/scala/com/resy/ResyApi.scala#L102) line of code is returning with the payment id and token and (2) where in the world you realized it would be named "struct_payment_method" - I don't see it mentioned [here](http://subzerocbd.info/#book). (EDIT: I did find this listed in the Network request on the actual website :) )

**Comment by btbeal** [comment]
Update: solved! Nevermind and thanks for the great code pointing me towards the solution!

For future users:

Oddly, the body of the request when the `Content-Type` = "application/x-www-form-urlencoded", is a url-like string. So, the body should read something like this (in R, as my language):

```
my_string <- paste0(
  'book_token=', book_token, '&struct_payment_method={\"id\":',payment_id,'}'
)
```

Probably obvious from `stringifyQueryParams` but... passing a url-like string to a body seemed odd to me.

**Comment by Alkaar** [comment]
Didn't quite follow your issue on the above but I'll just comment to the best of my ability.

> (1) the format [this](https://github.com/Alkaar/resy-booking-bot/blob/b6ba39813c5a033e0aed973fa0ccf204cdf79559/src/main/scala/com/resy/ResyApi.scala#L102) line of code is returning with the payment id and token

Regarding what the code is sending/receiving, there's a log4j file that you can simply flip from `info` to `debug` and it will spit out everything for you including what is in the post request.

> (2) where in the world you realized it would be named "struct_payment_method" - I don't see it mentioned [here](http://subzerocbd.info/#book).

That is actually not the official documentation and it didn't exactly line up with reality when I was actually testing. I linked it more for reference than a source of truth. I actually built this by just inspecting the requests/responses over the wire by manually making a reservation without using that documentation.

> Probably obvious from stringifyQueryParams but... passing a url-like string to a body seemed odd to me.

So `queryParams` is just a map data structure. I represented it as a map because it's easier to work with than building a string, plus it's more readable. `stringifyQueryParams` is then used to convert it into a format so it can be passed over the wire at the last mile.
