### ISSUE TITLE
staticlogger

### ISSUE THREAD

**Issue by doobert100** [Alkaar/resy-booking-bot#8]
This is probably something I'm doing wrong, but when I run it, I get

Attempting to snipe reservation at ______
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I've tried to troubleshoot, but so far haven't had success.  Any ideas?  Thank you

**Comment by doobert100** [comment]
Figured this one out, but unfortunately am now getting thrown a 419: unauthorized

**Comment by Alkaar** [comment]
Sorry for not keeping up to date on these issues as I've not used nor maintained the bot due to the pandemic. As of now, it seems that Resy updated the API endpoint so the contract is completely different. I have tried to go through the bot to fix things but I haven't gotten around to fixing it completely. Just wanted to make you all aware.

**Comment by Alkaar** [comment]
So I fixed the bot to work with the new Resy API along with a few minor fixes. Give it a shot and LMK how it goes.

I never set up a logger so left that error there. I basically threw everything to stdout. The 419 unauthorized error is likely due to you not passing the right auth headers.

**Comment by Alkaar** [comment]
Didn't hear back but I did fix this issue in this commit 👉 https://github.com/Alkaar/resy-booking-bot/commit/ede130c64617eddc2b403b601c1d91d021428c19
